### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by lisiang** [tsailabSJ/changeseq#6]
I had some problems while researching CHANGE seq, When I run
"changeseq.py all - manifest.YAML"
an error appears The error code is:
"usage: changeseq.py all [-h] --manifest MANIFEST [--sample SAMPLE]
changeseq.py all: error: argument --manifest/-m is required"
I don't understand what caused this error.

When I was running the "manifest.yaml" provided on GitHub https://github.com/tsailabSJ/changeseq  
 some necessary files are missing
"read1: /data/joung/sequencing_fastq/150902_M01326_0235_000000000-AHLT8/fastq/1_S1_L001_R1_001.fastq.gz
        read2: /data/joung/sequencing_fastq/150902_M01326_0235_000000000-AHLT8/fastq/1_S1_L001_R2_001.fastq.gz
        controlread1: /data/joung/sequencing_fastq/150902_M01326_0235_000000000-AHLT8/fastq/4_S4_L001_R1_001.fastq.gz
        controlread2: /data/joung/sequencing_fastq/150902_M01326_0235_000000000-AHLT8/fastq/4_S4_L001_R2_001.fastq.gz

read1: /data/joung/sequencing_fastq/150902_M01326_0235_000000000-AHLT8/fastq/2_S2_L001_R1_001.fastq.gz
        read2: /data/joung/sequencing_fastq/150902_M01326_0235_000000000-AHLT8/fastq/2_S2_L001_R2_001.fastq.gz
        controlread1: /data/joung/sequencing_fastq/150902_M01326_0235_000000000-AHLT8/fastq/4_S4_L001_R1_001.fastq.gz
        controlread2: /data/joung/sequencing_fastq/150902_M01326_0235_000000000-AHLT8/fastq/4_S4_L001_R2_001.fastq.gz"

If it is convenient, could you please upload the file you used to run the above "manifest.yaml"

**Comment by YichaoOU** [comment]
Hello,

Your command `changeseq.py all - manifest.YAML` is not valid, because just like the error message said, `-m is required`, you missed `-m`. So it should be `changeseq.py all -m manifest.YAML`.


In terms of testing, go to the test folder:

```
cd changeseq/test

changeseq.py all --manifest CIRCLEseq_MergedTest.yaml
```

Testing dataset is provided in that folder.

You can find some real change-seq data here: https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA625995

I think the sgRNA info is provided in the supplementary files.

Let me know if you need more help.

Yichao
